### ISSUE TITLE
Issue adding a bank

### ISSUE THREAD

**Issue by oddlots** [captin411/ofxmate#2]
OSX 10.9.4 
Getting transactions works fine but I needed to update a banks information. Using the webapp I found the bank and upon submit of the username and password get an internal 500 error with the following info:

Traceback (most recent call last):  File "cherrypy/_cprequest.pyc",
 line 656,
 in respond  File "cherrypy/lib/encoding.pyc",
 line 188,
 in __call__  File "cherrypy/_cpdispatch.pyc",
 line 34,
 in __call__  File "ofxmate/webapp/**init**.pyc",
 line 44,
 in add_bank  File "ofxhome/**init**.pyc",
 line 21,
 in lookup  File "ofxhome/**init**.pyc",
 line 112,
 in **init**  File "ofxhome/**init**.pyc",
 line 64,
 in _textIndexError: list index out of range

**Comment by oddlots** [comment]
Running OFXClient from the command line I am getting the following:

Traceback (most recent call last):
  File "/usr/local/bin/ofxclient", line 8, in <module>
    load_entry_point('ofxclient==1.3.8', 'console_scripts', 'ofxclient')()
  File "/Library/Python/2.7/site-packages/ofxclient-1.3.8-py2.7.egg/ofxclient/cli.py", line 43, in run
    main_menu()
  File "/Library/Python/2.7/site-packages/ofxclient-1.3.8-py2.7.egg/ofxclient/cli.py", line 63, in main_menu
    add_account_menu()
  File "/Library/Python/2.7/site-packages/ofxclient-1.3.8-py2.7.egg/ofxclient/cli.py", line 100, in add_account_menu
    bank = OFXHome.lookup(found[int(choice)]['id'])
  File "/Library/Python/2.7/site-packages/ofxhome-0.3.1-py2.7.egg/ofxhome/**init**.py", line 21, in lookup
  File "/Library/Python/2.7/site-packages/ofxhome-0.3.1-py2.7.egg/ofxhome/**init**.py", line 112, in **init**
  File "/Library/Python/2.7/site-packages/ofxhome-0.3.1-py2.7.egg/ofxhome/**init**.py", line 64, in _text
IndexError: list index out of range
